import { existsSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import { basename, dirname } from "node:path";
import type { PlanAssumption, PlanQuestion, ScanSignal } from "../types.ts";
import { normalizeSlash, resolveInsideRoot } from "../safety/pathPolicy.ts";

const IGNORE_DIRS = new Set(["Library", "Temp", "obj", "Build", "Builds", "Logs", "UserSettings", ".vs", ".idea", "node_modules"]);
const ENTRY_SCENE_NAMES = new Set(["Launch.unity", "Bootstrap.unity", "Start.unity", "Main.unity", "Init.unity"]);
const BOOTSTRAP_NAMES = ["Bootstrap", "GameBootstrap", "AppBootstrap", "Launcher", "Launch", "GameRoot", "AppRoot", "Startup", "StartUp", "Entry"];
const RESOURCE_DIRS = new Set(["Resources", "AddressableAssetsData", "StreamingAssets", "AssetBundles", "Bundles", "Art", "Arts", "ArtResources", "Res", "ResourcesAssets", "Prefabs", "UI", "Audio", "Sounds", "VFX", "Effects", "Materials", "Shaders", "Textures", "Sprites", "Fonts"]);
const GENERATED_DIR_PARTS = new Set(["Generated", "Gen", "AutoGenerated", "GeneratedCode"]);

export interface UnityAssemblyInfo {
  name: string;
  path: string;
  type: "runtime" | "editor";
  references: string[];
  includePlatforms: string[];
  excludePlatforms: string[];
}

export interface UnityScannerResult {
  confidence: number;
  signals: ScanSignal[];
  warnings: Array<{ code: string; message: string; path?: string }>;
  questions: PlanQuestion[];
  assumptions: PlanAssumption[];
  facts: {
    unity: {
      version: string | null;
      versionSource: string;
      packages: Record<string, boolean>;
      renderPipeline: { candidate: "URP" | "HDRP" | "Built-in or unknown"; confidence: number; evidence: string[] };
      assemblies: { runtime: UnityAssemblyInfo[]; editor: UnityAssemblyInfo[] };
      entryScene: { path: string | null; confidence: number; candidates: string[] };
      bootstrap: { candidates: Array<{ path: string; confidence: number; evidence: string[] }> };
      resources: { systems: Array<{ name: string; source: string; confidence: number; evidence: string[] }>; roots: Array<{ path: string; type: string; confidence: number }> };
      generated: { candidates: Array<{ path: string; kind: string; confidence: number }> };
    };
  };
}

async function walk(root: string, rel = "", out: string[] = []): Promise<string[]> {
  const abs = resolveInsideRoot(root, rel || ".");
  let entries;
  try {
    entries = await readdir(abs, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries) {
    if (entry.isDirectory() && IGNORE_DIRS.has(entry.name)) continue;
    const childRel = normalizeSlash(rel ? `${rel}/${entry.name}` : entry.name);
    if (entry.isDirectory()) await walk(root, childRel, out);
    else if (entry.isFile()) out.push(childRel);
  }
  return out;
}

async function readSmallText(root: string, rel: string, maxBytes = 256_000): Promise<string> {
  const abs = resolveInsideRoot(root, rel);
  const buffer = await readFile(abs);
  if (buffer.byteLength > maxBytes) return buffer.subarray(0, maxBytes).toString("utf8");
  return buffer.toString("utf8");
}

export function parseUnityVersion(text: string): string | null {
  const match = text.match(/^m_EditorVersion:\s*(.+?)\s*$/m);
  return match?.[1]?.trim() ?? null;
}

export async function scanUnityProject(root: string): Promise<UnityScannerResult> {
  const signals: ScanSignal[] = [];
  const warnings: UnityScannerResult["warnings"] = [];
  const questions: PlanQuestion[] = [];
  const assumptions: PlanAssumption[] = [];
  let confidence = 0;

  function addSignal(type: string, path: string, weight: number): void {
    confidence += weight;
    signals.push({ type, path, profile: "unity", weight });
  }

  if (existsSync(resolveInsideRoot(root, "ProjectSettings/ProjectVersion.txt"))) addSignal("file_exists", "ProjectSettings/ProjectVersion.txt", 0.45);
  if (existsSync(resolveInsideRoot(root, "Assets"))) addSignal("dir_exists", "Assets", 0.25);
  if (existsSync(resolveInsideRoot(root, "Packages/manifest.json"))) addSignal("file_exists", "Packages/manifest.json", 0.20);
  if (existsSync(resolveInsideRoot(root, "ProjectSettings/ProjectSettings.asset"))) addSignal("file_exists", "ProjectSettings/ProjectSettings.asset", 0.05);

  const files = await walk(root);
  const sceneFiles = files.filter((file) => file.endsWith(".unity") && file.startsWith("Assets/"));
  if (sceneFiles.length > 0) addSignal("file_glob_exists", "Assets/**/*.unity", 0.05);
  confidence = Math.min(1, confidence);

  let version: string | null = null;
  if (existsSync(resolveInsideRoot(root, "ProjectSettings/ProjectVersion.txt"))) {
    const versionText = await readSmallText(root, "ProjectSettings/ProjectVersion.txt");
    version = parseUnityVersion(versionText);
    if (!version) warnings.push({ code: "unity_version_unparsed", message: "ProjectVersion.txt exists but m_EditorVersion could not be parsed.", path: "ProjectSettings/ProjectVersion.txt" });
  }

  const dependencies: Record<string, string> = {};
  if (existsSync(resolveInsideRoot(root, "Packages/manifest.json"))) {
    try {
      const manifest = JSON.parse(await readSmallText(root, "Packages/manifest.json")) as { dependencies?: Record<string, string> };
      Object.assign(dependencies, manifest.dependencies ?? {});
    } catch (error) {
      warnings.push({ code: "manifest_parse_failed", message: `Failed to parse Packages/manifest.json: ${String(error)}`, path: "Packages/manifest.json" });
    }
  }

  const packages = {
    addressables: Boolean(dependencies["com.unity.addressables"]),
    urp: Boolean(dependencies["com.unity.render-pipelines.universal"]),
    hdrp: Boolean(dependencies["com.unity.render-pipelines.high-definition"]),
    inputSystem: Boolean(dependencies["com.unity.inputsystem"]),
    testFramework: Boolean(dependencies["com.unity.test-framework"]),
    timeline: Boolean(dependencies["com.unity.timeline"]),
    cinemachine: Boolean(dependencies["com.unity.cinemachine"]),
  };

  const resourceSystems: Array<{ name: string; source: string; confidence: number; evidence: string[] }> = [];
  if (packages.addressables) {
    resourceSystems.push({ name: "Addressables", source: "Packages/manifest.json", confidence: 0.8, evidence: ["com.unity.addressables"] });
  } else {
    assumptions.push({ id: "a-resource-system-generic", text: "No known Unity resource package was detected; resource rules stay generic.", risk: "low" });
  }

  const renderPipeline = packages.urp
    ? { candidate: "URP" as const, confidence: 0.7, evidence: ["Packages/manifest.json contains com.unity.render-pipelines.universal"] }
    : packages.hdrp
      ? { candidate: "HDRP" as const, confidence: 0.7, evidence: ["Packages/manifest.json contains com.unity.render-pipelines.high-definition"] }
      : { candidate: "Built-in or unknown" as const, confidence: 0.1, evidence: [] };

  const assemblies: UnityAssemblyInfo[] = [];
  for (const file of files.filter((f) => f.endsWith(".asmdef") && f.startsWith("Assets/"))) {
    try {
      const data = JSON.parse(await readSmallText(root, file)) as { name?: string; references?: string[]; includePlatforms?: string[]; excludePlatforms?: string[] };
      const includePlatforms = data.includePlatforms ?? [];
      const type = file.split("/").includes("Editor") || includePlatforms.includes("Editor") ? "editor" : "runtime";
      assemblies.push({ name: data.name ?? file, path: file, type, references: data.references ?? [], includePlatforms, excludePlatforms: data.excludePlatforms ?? [] });
    } catch (error) {
      warnings.push({ code: "asmdef_parse_failed", message: `Failed to parse asmdef: ${String(error)}`, path: file });
    }
  }
  const editorNames = new Set(assemblies.filter((a) => a.type === "editor").map((a) => a.name));
  for (const asm of assemblies.filter((a) => a.type === "runtime")) {
    const badRef = asm.references.find((ref) => editorNames.has(ref.replace(/^GUID:/, "")));
    if (badRef) {
      questions.push({ id: `q-runtime-references-editor-${asm.name}`, severity: "blocking", question: `Runtime assembly ${asm.name} references Editor assembly ${badRef}.`, reason: "Runtime assemblies must not reference Editor assemblies." });
    }
  }

  for (const file of files.filter((f) => f.endsWith(".cs") && f.startsWith("Assets/"))) {
    const text = await readSmallText(root, file, 128_000);
    if ((text.includes("using UnityEditor;") || text.includes("UnityEditor.")) && !file.split("/").includes("Editor") && !text.includes("#if UNITY_EDITOR")) {
      warnings.push({ code: "unityeditor_reference_outside_editor", message: "UnityEditor reference found outside Editor folder; verify asmdef/platform guards.", path: file });
    }
  }

  const entryCandidates = sceneFiles.filter((file) => ENTRY_SCENE_NAMES.has(basename(file)));
  if (entryCandidates.length > 1) {
    questions.push({ id: "q-entry-scene", severity: "blocking", question: "Multiple possible entry scenes were detected. Which one is the startup scene?", options: entryCandidates, reason: "Entry scene affects the generated bootstrap facts." });
  }
  const entryScene = entryCandidates[0] ?? sceneFiles[0] ?? null;

  const bootstrapCandidates: Array<{ path: string; confidence: number; evidence: string[] }> = [];
  for (const file of files.filter((f) => f.endsWith(".cs") && f.startsWith("Assets/"))) {
    const base = basename(file, ".cs");
    const evidence: string[] = [];
    if (BOOTSTRAP_NAMES.some((name) => base.includes(name))) evidence.push(`filename contains ${base}`);
    const text = await readSmallText(root, file, 128_000);
    for (const marker of ["DontDestroyOnLoad", "SceneManager.LoadScene", "Addressables.InitializeAsync", "Application.targetFrameRate", "Awake()", "Start()"] as const) {
      if (text.includes(marker)) evidence.push(`contains ${marker}`);
    }
    if (evidence.length > 0) bootstrapCandidates.push({ path: file, confidence: Math.min(0.3 + evidence.length * 0.12, 0.9), evidence });
  }
  bootstrapCandidates.sort((a, b) => b.confidence - a.confidence);

  const resourceRoots: Array<{ path: string; type: string; confidence: number }> = [];
  for (const file of files) {
    const parts = dirname(file).split("/").filter(Boolean);
    for (const part of parts) {
      if (!RESOURCE_DIRS.has(part)) continue;
      const idx = parts.indexOf(part);
      const path = parts.slice(0, idx + 1).join("/");
      if (!resourceRoots.some((root) => root.path === path)) {
        const type = part === "Resources" ? "unity_resources" : part === "AddressableAssetsData" ? "addressables_config" : "runtime_assets";
        resourceRoots.push({ path, type, confidence: part === "AddressableAssetsData" ? 0.9 : part === "Resources" ? 0.8 : 0.5 });
      }
    }
  }
  if (resourceRoots.length === 0) {
    assumptions.push({ id: "a-resource-root-undetected", text: "No dedicated runtime resource root was detected; Assets/** remains the broad Unity asset source until project spec narrows it.", risk: "low" });
  }

  const generatedCandidates: Array<{ path: string; kind: string; confidence: number }> = [];
  for (const file of files.filter((f) => f.startsWith("Assets/"))) {
    const parts = file.split("/");
    if (parts.some((part) => GENERATED_DIR_PARTS.has(part))) generatedCandidates.push({ path: file, kind: "generated_path", confidence: 0.7 });
    if (/\.(g|generated|Designer)\.cs$/i.test(file) || file.endsWith(".BindComponents.cs")) generatedCandidates.push({ path: file, kind: "generated_code", confidence: 0.8 });
  }
  if (generatedCandidates.length > 0) {
    questions.push({ id: "q-generated-policy", severity: "non_blocking", question: "Generated files were detected. Should they be edited manually or treated as generated output?", options: ["do_not_edit_generated", "project_specific_policy_needed"], reason: "Generated output source-of-truth policy should not be guessed." });
  }

  return {
    confidence,
    signals,
    warnings,
    questions,
    assumptions,
    facts: {
      unity: {
        version,
        versionSource: "ProjectSettings/ProjectVersion.txt",
        packages,
        renderPipeline,
        assemblies: { runtime: assemblies.filter((a) => a.type === "runtime"), editor: assemblies.filter((a) => a.type === "editor") },
        entryScene: { path: entryScene, confidence: entryCandidates.length === 1 ? 0.75 : entryScene ? 0.4 : 0, candidates: entryCandidates.length > 0 ? entryCandidates : sceneFiles },
        bootstrap: { candidates: bootstrapCandidates.slice(0, 8) },
        resources: { systems: resourceSystems, roots: resourceRoots },
        generated: { candidates: generatedCandidates },
      },
    },
  };
}
